In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

In [112]:
df = pd.read_csv("classification_data.csv")
df.head(2)

count_session  count_hit channelGrouping  totals_newVisits  \
0              9       1194         (Other)                 0   
1              9       1194         (Other)                 0   

    device_browser device_operatingSystem  device_isMobile  \
0  GoogleAnalytics                Android             True   
1  GoogleAnalytics                Android             True   

  device_deviceCategory geoNetwork_region  geoNetwork_latitude  ...  \
0                mobile           Sharjah              25.3463  ...   
1                mobile           Sharjah              25.3463  ...   

   latest_keyword  earliest_isTrueDirect  latest_isTrueDirect  \
0       (not set)                   True                 True   
1       (not set)                   True                 True   

   num_interactions  bounces  time_on_site  transactionRevenue  \
0              1900        0          5617                   0   
1              1900        0          5617                   0   

         products_array  has_converted  target_date  
0  food////food////food              0   2021-01-01  
1  food////food////food              0   2021-01-01  

[2 rows x 46 columns]

In [113]:
df['channelGrouping'].unique()

array(['(Other)', 'Paid Search', 'Display'], dtype=object)

In [114]:
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   count_session           100000 non-null  int64  
 1   count_hit               100000 non-null  int64  
 2   channelGrouping         100000 non-null  object 
 3   totals_newVisits        100000 non-null  int64  
 4   device_browser          100000 non-null  object 
 5   device_operatingSystem  100000 non-null  object 
 6   device_isMobile         100000 non-null  bool   
 7   device_deviceCategory   100000 non-null  object 
 8   geoNetwork_region       100000 non-null  object 
 9   geoNetwork_latitude     100000 non-null  float64
 10  geoNetwork_longitude    100000 non-null  float64
 11  historic_session        100000 non-null  int64  
 12  historic_session_page   100000 non-null  int64  
 13  youtube                 100000 non-null  int64  
 14  avg_session_time     

STATIC ANALYSIS

In [115]:
from scipy.stats import ttest_ind
from scipy.stats import chi2_contingency

In [116]:
# T-Test for significance

converted = df[df['has_converted'] == 1]['avg_session_time']
not_converted = df[df['has_converted'] == 0]['avg_session_time']

t_stat, p_value = ttest_ind(converted, not_converted, equal_var=False)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

T-Statistic: -101.68281986021069
P-Value: 0.0


In [117]:
# Chi-Square Test for Independence

observed = pd.crosstab(df['device_browser'], df['has_converted'])
chi2_stat, p_value, dof, expected = chi2_contingency(observed)

print("Chi-Square Statistic:", chi2_stat)
print("P-Value:", p_value)

Chi-Square Statistic: 3714.293608203444
P-Value: 0.0


In [118]:
from scipy.stats import f_oneway

# Exclude the '(Other)' category from the analysis
group1 = df[df['channelGrouping'] == 'Paid Search']['count_hit']
group2 = df[df['channelGrouping'] == 'Display']['count_hit']

f_stat, p_value = f_oneway(group1, group2)
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

F-statistic: 63.92988303909886
P-value: 1.3029201590503486e-15


In [119]:
print("Group Sizes:")
print("Group A:", len(group1))
print("Group B:", len(group2))

Group Sizes:
Group A: 87948
Group B: 12050


In [120]:
print("Distribution of channelGrouping:")
print(df['channelGrouping'].value_counts())

Distribution of channelGrouping:
channelGrouping
Paid Search    87948
Display        12050
(Other)            2
Name: count, dtype: int64


In [121]:
df.to_csv("df1.csv",index= False)

ENCIDING

In [207]:
import pandas as pd

In [208]:
df1=pd.read_csv("df1.csv")
df1.head(2)

count_session  count_hit channelGrouping  totals_newVisits  \
0              9       1194         (Other)                 0   
1              9       1194         (Other)                 0   

    device_browser device_operatingSystem  device_isMobile  \
0  GoogleAnalytics                Android             True   
1  GoogleAnalytics                Android             True   

  device_deviceCategory geoNetwork_region  geoNetwork_latitude  ...  \
0                mobile           Sharjah              25.3463  ...   
1                mobile           Sharjah              25.3463  ...   

   latest_keyword  earliest_isTrueDirect  latest_isTrueDirect  \
0       (not set)                   True                 True   
1       (not set)                   True                 True   

   num_interactions  bounces  time_on_site  transactionRevenue  \
0              1900        0          5617                   0   
1              1900        0          5617                   0   

         products_array  has_converted  target_date  
0  food////food////food              0   2021-01-01  
1  food////food////food              0   2021-01-01  

[2 rows x 46 columns]

In [124]:
obje_col = df1.select_dtypes(include=['object'])
obje_col.head(3)

channelGrouping   device_browser device_operatingSystem  \
0         (Other)  GoogleAnalytics                Android   
1         (Other)  GoogleAnalytics                Android   
2     Paid Search  GoogleAnalytics                Android   

  device_deviceCategory geoNetwork_region earliest_source latest_source  \
0                mobile           Sharjah        gulfnews      gulfnews   
1                mobile           Sharjah        gulfnews      gulfnews   
2                mobile             Ajman        (direct)        google   

  earliest_medium latest_medium earliest_keyword        latest_keyword  \
0             app           app        (not set)             (not set)   
1             app           app        (not set)             (not set)   
2          (none)           cpc        (not set)  (automatic matching)   

                                      products_array target_date  
0                               food////food////food  2021-01-01  
1                               food////food////food  2021-01-01  
2  (not set)////baby_products--milk,_food_&_juice...  2021-01-01

In [125]:
obje_col.columns

Index(['channelGrouping', 'device_browser', 'device_operatingSystem',
       'device_deviceCategory', 'geoNetwork_region', 'earliest_source',
       'latest_source', 'earliest_medium', 'latest_medium', 'earliest_keyword',
       'latest_keyword', 'products_array', 'target_date'],
      dtype='object')

In [126]:
# cat col unique val
for column in obje_col.columns:
    unique_values = df1[column].unique()
    unique_sum = len(unique_values)
    print(f" '{column}': {unique_sum}")

 'channelGrouping': 3
 'device_browser': 9
 'device_operatingSystem': 7
 'device_deviceCategory': 3
 'geoNetwork_region': 91
 'earliest_source': 36
 'latest_source': 7
 'earliest_medium': 18
 'latest_medium': 2
 'earliest_keyword': 410
 'latest_keyword': 572
 'products_array': 3559
 'target_date': 1


In [127]:
obje_col['products_array'].unique()

array(['food////food////food',
       '(not set)////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(1-6_years)////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////(not set)////(not set)////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////food////(not set)////(not set)////food////food////food////food////food////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////food////food////food////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food

In [128]:
from sklearn.preprocessing import OrdinalEncoder

In [129]:
df1['device_browser'].unique()

array(['GoogleAnalytics', 'Safari', 'Chrome', 'Edge', 'Firefox',
       'Samsung Internet', 'Opera', 'Android Webview',
       'Apache-HttpClient'], dtype=object)

In [130]:
# Assuming 'device_browser' is the name of the column you want to convert
browser_mapping = {'GoogleAnalytics': 1, 'Safari': 2, 'Chrome': 3, 'Edge': 4, 'Firefox': 5, 'Samsung Internet': 6, 'Opera': 7,
                   'Android Webview': 8, 'Apache-HttpClient': 9}

df1['device_browser'] = df1['device_browser'].map(browser_mapping)


In [131]:
df1['device_browser'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [132]:
df1['latest_source'].unique()

array(['gulfnews', 'google', 'Pricena_AE', 'facebook', 'criteo', 'yaoota',
       'Pricena_AE_Home'], dtype=object)

In [133]:
# Assuming 'latest_source' is the name of the column you want to convert
source_mapping = {'gulfnews': 1, 'google': 2, 'Pricena_AE': 3, 'facebook': 4, 'criteo': 5,
                  'yaoota': 6, 'Pricena_AE_Home': 7}
df1['latest_source'] = df1['latest_source'].map(source_mapping)

In [134]:
df1['geoNetwork_region'].unique()

array(['Sharjah', 'Ajman', 'Abu Dhabi', 'Dubai', 'Ras al Khaimah',
       '(not set)', 'England', 'Hessen', 'Ash Sharqia Governorate',
       'Nabatiyeh Governorate', 'Umm Al Quawain', 'Indiana', 'Illinois',
       'Makkah Province', 'Maharashtra', 'Capital Governorate', 'Jakarta',
       'Punjab', 'Mount Lebanon Governorate', 'South Holland',
       'Riyadh Province', 'Ile-de-France', 'Chandigarh', 'Karnataka',
       'Istanbul', 'Cairo Governorate', 'Andhra Pradesh',
       'Amman Governorate', 'Beirut Governorate',
       'Alexandria Governorate', 'New York', 'Ontario', 'Davao Region',
       'Auvergne-Rhone-Alpes', 'Fujairah', 'Tamil Nadu',
       'Pays de la Loire', 'Metro Manila', 'Normandy', 'Giza Governorate',
       'Bavaria', 'Stockholm County', 'Tel Aviv District', 'Vienna',
       'Decentralized Administration of Peloponnese, Western Greece and the Ionian',
       'Porto District', 'West Bengal', 'Kerala', 'Lombardy', 'MIMAROPA',
       'North Holland', 'Chiba', 'Islamabad 

In [135]:
df1['geoNetwork_region'] = df1['geoNetwork_region'].astype('category').cat.codes

In [136]:
df1['geoNetwork_region'].unique()

array([71,  2,  1, 25, 68,  0, 27, 36,  6, 56, 82, 39, 38, 51, 50, 15, 43,
       66, 54, 74, 69, 37, 19, 44, 42, 13,  5,  4, 11,  3, 58, 63, 23,  9,
       32, 77, 64, 52, 59, 33, 10, 76, 79, 85, 24, 65, 88, 45, 47, 48, 60,
       20, 40, 62, 31, 53, 21, 67, 55, 80, 84, 89, 61, 72, 86, 14, 70, 17,
       22, 90, 30, 28, 87, 78, 26, 29, 34, 75, 49, 41, 83, 16, 57, 73,  8,
       81, 46, 35,  7, 12, 18], dtype=int8)

In [137]:
# 'earliest_medium'
df1['earliest_medium'] = df1['earliest_medium'].astype('category').cat.codes

# 'earliest_keyword'
df1['earliest_keyword'] = df1['earliest_keyword'].astype('category').cat.codes

# 'latest_keyword'
df1['latest_keyword'] = df1['latest_keyword'].astype('category').cat.codes

# 'latest_keyword'
df1['earliest_source'] = df1['earliest_source'].astype('category').cat.codes


In [138]:
df1['products_array'].unique()

array(['food////food////food',
       '(not set)////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(1-6_years)////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////(not set)////(not set)////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////food////(not set)////(not set)////food////food////food////food////food////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////food////food////food////baby_products--milk,_food_&_juices--baby_&_toddler_formula--baby_formula_(6-12_years)////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food////food

In [139]:
# 'latest_keyword'
df1['products_array'] = df1['products_array'].astype('category').cat.codes

In [140]:
df1['products_array'].unique()

array([2265,  898, 2234, ..., 1984, 1225, 1353], dtype=int16)

In [141]:
df1['device_deviceCategory'].unique()

array(['mobile', 'desktop', 'tablet'], dtype=object)

In [142]:
# convert through Encodeing
df1["device_deviceCategory"]= df1["device_deviceCategory"].map({'mobile':1, 'desktop':2, 'tablet':3})

In [143]:
df1['latest_medium'].unique()

array(['app', 'cpc'], dtype=object)

In [144]:
# convert through Encodeing
df1["latest_medium"]= df1["latest_medium"].map({'app':1, 'cpc':2})

In [145]:
df1['target_date']

0        2021-01-01
1        2021-01-01
2        2021-01-01
3        2021-01-01
4        2021-01-01
            ...    
99995    2021-01-01
99996    2021-01-01
99997    2021-01-01
99998    2021-01-01
99999    2021-01-01
Name: target_date, Length: 100000, dtype: object

In [146]:
# Assuming 'column_name' is the name of the column you want to convert to datetime
df1['target_date'] = pd.to_datetime(df1['target_date'], errors='coerce')

df['target_date'] = pd.to_datetime(df['target_date'], format='%Y-%m-%d', errors='coerce')
df['target_date']

0       2021-01-01
1       2021-01-01
2       2021-01-01
3       2021-01-01
4       2021-01-01
           ...    
99995   2021-01-01
99996   2021-01-01
99997   2021-01-01
99998   2021-01-01
99999   2021-01-01
Name: target_date, Length: 100000, dtype: datetime64[ns]

In [147]:
df1['channelGrouping'].unique()

array(['(Other)', 'Paid Search', 'Display'], dtype=object)

In [148]:
# convert through Encodeing
df1["channelGrouping"]= df1["channelGrouping"].map({'other':1, 'Paid Search':2, 'Display':3})

In [149]:
df1['channelGrouping'].unique()

array([nan,  2.,  3.])

In [150]:
df1['device_operatingSystem'].unique()

array(['Android', 'iOS', 'Macintosh', 'Windows', 'Chrome OS', '(not set)',
       'Linux'], dtype=object)

In [151]:
# convert through Encodeing
df1["device_operatingSystem"]= df1["device_operatingSystem"].map({'Android':1, 'iOS':2, 'Macintosh':3, 'Windows':0, 'Chrome OS':4,
                                '(not set)':5, 'Linux':6})

In [152]:
df1['device_operatingSystem'].unique()

array([1, 2, 3, 0, 4, 5, 6], dtype=int64)

In [153]:
df1.columns

Index(['count_session', 'count_hit', 'channelGrouping', 'totals_newVisits',
       'device_browser', 'device_operatingSystem', 'device_isMobile',
       'device_deviceCategory', 'geoNetwork_region', 'geoNetwork_latitude',
       'geoNetwork_longitude', 'historic_session', 'historic_session_page',
       'youtube', 'avg_session_time', 'avg_session_time_page',
       'single_page_rate', 'sessionQualityDim', 'last_visitId',
       'latest_visit_id', 'visitId_threshold', 'earliest_visit_id',
       'earliest_visit_number', 'latest_visit_number', 'time_earliest_visit',
       'time_latest_visit', 'avg_visit_time', 'days_since_last_visit',
       'days_since_first_visit', 'visits_per_day', 'bounce_rate',
       'earliest_source', 'latest_source', 'earliest_medium', 'latest_medium',
       'earliest_keyword', 'latest_keyword', 'earliest_isTrueDirect',
       'latest_isTrueDirect', 'num_interactions', 'bounces', 'time_on_site',
       'transactionRevenue', 'products_array', 'has_converted', 't

In [154]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                  Non-Null Count   Dtype         
---  ------                  --------------   -----         
 0   count_session           100000 non-null  int64         
 1   count_hit               100000 non-null  int64         
 2   channelGrouping         99998 non-null   float64       
 3   totals_newVisits        100000 non-null  int64         
 4   device_browser          100000 non-null  int64         
 5   device_operatingSystem  100000 non-null  int64         
 6   device_isMobile         100000 non-null  bool          
 7   device_deviceCategory   100000 non-null  int64         
 8   geoNetwork_region       100000 non-null  int8          
 9   geoNetwork_latitude     100000 non-null  float64       
 10  geoNetwork_longitude    100000 non-null  float64       
 11  historic_session        100000 non-null  int64         
 12  historic_session_page   100000 

binning and Discretization of this columns. Because its have huge level of uniques values.

In [ ]:
import pandas as pd

# Assuming df1 is your DataFrame containing the data
bins = {
    'avg_session_time': [0, 1000, 5000, float('inf')],  # Define your bins for avg_session_time
    'count_hit': [0, 100, 1000, float('inf')],          # Define your bins for count_hit
    'num_interactions': [0, 1000, 5000, float('inf')]   # Define your bins for num_interactions
}

labels = ['low', 'medium', 'high']  # Define labels for each bin

# Bin the numerical columns
for column, bin_edges in bins.items():
    df1[column + '_binned'] = pd.cut(df1[column], bins=bin_edges, labels=labels, right=False)

# Drop the original numerical columns
df1.drop(columns=['avg_session_time', 'avg_session_time', 'num_interactions'], inplace=True)

# Display the modified DataFrame
print(df1)


In [156]:
df1['avg_session_time_binned'].unique()

['low', 'medium', 'high']
Categories (3, object): ['low' < 'medium' < 'high']

In [157]:
df1['count_hit_binned'].unique()

['high', 'medium', 'low']
Categories (3, object): ['low' < 'medium' < 'high']

In [158]:
df1['num_interactions_binned'].unique()

['medium', 'low', 'high']
Categories (3, object): ['low' < 'medium' < 'high']

In [161]:
df1["avg_session_time_binned"]= df1["avg_session_time_binned"].map({'low':1, 'medium':2, 'high':3})
df1["count_hit_binned"]= df1["count_hit_binned"].map({'low':1, 'medium':2, 'high':3})
df1["num_interactions_binned"]= df1["num_interactions_binned"].map({'low':1, 'medium':2, 'high':3})


In [209]:
df1["sessionQualityDim"]

0         6
1         6
2         4
3        42
4        42
         ..
99995    11
99996    11
99997    11
99998    11
99999    11
Name: sessionQualityDim, Length: 100000, dtype: int64

In [210]:
df1['single_page_rate'].unique()

array([0.77777778, 0.82142857, 1.        , 0.4       , 0.98701299,
       0.92857143, 0.96296296, 0.75      , 0.25      , 0.66666667,
       0.83673469, 0.175     , 0.88888889, 0.86363636, 0.73913043,
       0.97058824, 0.98507463, 0.91428571, 0.625     , 0.        ,
       0.14285714, 0.93333333, 0.97368421, 0.71428571, 0.8       ,
       0.93589744, 0.81818182, 0.94444444, 0.5       , 0.90909091,
       0.33333333, 0.83333333, 0.9       , 0.6       , 0.97560976,
       0.89473684, 0.96666667, 0.41666667, 0.63157895, 0.125     ,
       0.95238095, 0.76923077, 0.16666667, 0.94814815, 0.78571429,
       0.94117647, 0.95833333, 0.92307692, 0.88235294, 0.76470588,
       0.96551724, 0.80645161, 0.58823529, 0.28571429, 0.95      ,
       0.85714286, 0.61111111, 0.93181818, 0.2       , 0.78787879,
       0.63333333, 0.88461538, 0.93548387, 0.97727273, 0.76296296,
       0.95918367, 0.875     , 0.98113208, 0.36363636, 0.95454545,
       0.87037037, 0.7       , 0.94736842, 0.95652174, 0.94366

In [ ]:
# # selected_features
# sessionQualityDim
# avg_session_time_binned
# single_page_rate
# count_hit_binned
# num_interactions_binned


In [201]:
df1['sessionQualityDim'].unique()

array([ 4., 42.,  2.,  5., 25., 44.,  1., 45.,  8.,  6.,  3.,  7., 54.,
       10., 15., 41., 16., 24., 11., 21., 18., 53., 48., 39., 19., 40.,
       50., 22., 55., 49.,  9., 23., 17., 37., 14., 46., 43., 52., 56.,
       20., 51., 12., 27., 47., 34., 13., 38., 36.])

In [200]:
df1['single_page_rate'].unique()

array([0.82142857, 1.        , 0.98701299, 0.92857143, 0.96296296,
       0.75      , 0.25      , 0.66666667, 0.83673469, 0.88888889,
       0.86363636, 0.73913043, 0.97058824, 0.98507463, 0.91428571,
       0.93333333, 0.97368421, 0.8       , 0.81818182, 0.94444444,
       0.90909091, 0.33333333, 0.83333333, 0.9       , 0.6       ,
       0.89473684, 0.63157895, 0.97560976, 0.95238095, 0.76923077,
       0.78571429, 0.94117647, 0.92307692, 0.88235294, 0.71428571,
       0.76470588, 0.96551724, 0.95      , 0.85714286, 0.96666667,
       0.93181818, 0.78787879, 0.88461538, 0.93548387, 0.97727273,
       0.875     , 0.80645161, 0.87037037, 0.61111111, 0.7       ,
       0.95652174, 0.11111111, 0.91525424, 0.78947368, 0.77419355,
       0.5       , 0.95384615, 0.91304348, 0.64285714, 0.45454545,
       0.89189189, 0.95833333, 0.46875   , 0.93103448, 0.73076923,
       0.91666667, 0.96491228, 0.96153846, 0.98360656, 0.9375    ,
       0.70588235, 0.87096774, 0.84210526, 0.95454545, 0.55555

In [164]:
df1.columns

Index(['count_session', 'count_hit', 'channelGrouping', 'totals_newVisits',
       'device_browser', 'device_operatingSystem', 'device_isMobile',
       'device_deviceCategory', 'geoNetwork_region', 'geoNetwork_latitude',
       'geoNetwork_longitude', 'historic_session', 'historic_session_page',
       'youtube', 'avg_session_time_page', 'single_page_rate',
       'sessionQualityDim', 'last_visitId', 'latest_visit_id',
       'visitId_threshold', 'earliest_visit_id', 'earliest_visit_number',
       'latest_visit_number', 'time_earliest_visit', 'time_latest_visit',
       'avg_visit_time', 'days_since_last_visit', 'days_since_first_visit',
       'visits_per_day', 'bounce_rate', 'earliest_source', 'latest_source',
       'earliest_medium', 'latest_medium', 'earliest_keyword',
       'latest_keyword', 'earliest_isTrueDirect', 'latest_isTrueDirect',
       'bounces', 'time_on_site', 'transactionRevenue', 'products_array',
       'has_converted', 'target_date', 'avg_session_time_binned',


OUTLIERS find & Handling

In [165]:
import numpy as np

In [166]:
# Assuming 'df1' is your DataFrame
numeric_columns = df1.select_dtypes(include=[np.number]).columns
z_scores = np.abs((df1[numeric_columns] - df1[numeric_columns].mean()) / df1[numeric_columns].std())

# Set a threshold (e.g., 3) for z-scores
threshold = 3
outliers = (z_scores > threshold).any(axis=1)

# Handle outliers (replace with NaN, remove, or apply a transformation)
df1[outliers] = np.nan  # Replace outliers with NaN
# OR
df1 = df1[~outliers]  

C:\Users\Tprab\AppData\Local\Temp\ipykernel_10956\1954681814.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1[outliers] = np.nan  # Replace outliers with NaN
C:\Users\Tprab\AppData\Local\Temp\ipykernel_10956\1954681814.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1[outliers] = np.nan  # Replace outliers with NaN
C:\Users\Tprab\AppData\Local\Temp\ipykernel_10956\1954681814.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1[outliers] = np.nan  # 

In [167]:
df1.head(2)

count_session  count_hit  channelGrouping  totals_newVisits  \
2           28.0     1816.0              2.0               0.0   
3            2.0      299.0              2.0               0.0   

   device_browser  device_operatingSystem device_isMobile  \
2             1.0                     1.0            True   
3             1.0                     1.0            True   

   device_deviceCategory  geoNetwork_region  geoNetwork_latitude  ...  \
2                    1.0                2.0              25.4052  ...   
3                    1.0                1.0              24.4539  ...   

   latest_isTrueDirect  bounces  time_on_site  transactionRevenue  \
2                 True      0.0       77417.0        1.477195e+09   
3                 True      0.0        1576.0        0.000000e+00   

   products_array  has_converted  target_date  avg_session_time_binned  \
2           898.0            1.0   2021-01-01                        1   
3          2234.0            0.0   2021-01-01                        1   

   count_hit_binned  num_interactions_binned  
2                 3                        2  
3                 2                        1  

[2 rows x 47 columns]

In [168]:
df1.to_csv("df2.csv",index= False)

Future selectionign

In [169]:
df1.columns

Index(['count_session', 'count_hit', 'channelGrouping', 'totals_newVisits',
       'device_browser', 'device_operatingSystem', 'device_isMobile',
       'device_deviceCategory', 'geoNetwork_region', 'geoNetwork_latitude',
       'geoNetwork_longitude', 'historic_session', 'historic_session_page',
       'youtube', 'avg_session_time_page', 'single_page_rate',
       'sessionQualityDim', 'last_visitId', 'latest_visit_id',
       'visitId_threshold', 'earliest_visit_id', 'earliest_visit_number',
       'latest_visit_number', 'time_earliest_visit', 'time_latest_visit',
       'avg_visit_time', 'days_since_last_visit', 'days_since_first_visit',
       'visits_per_day', 'bounce_rate', 'earliest_source', 'latest_source',
       'earliest_medium', 'latest_medium', 'earliest_keyword',
       'latest_keyword', 'earliest_isTrueDirect', 'latest_isTrueDirect',
       'bounces', 'time_on_site', 'transactionRevenue', 'products_array',
       'has_converted', 'target_date', 'avg_session_time_binned',


In [170]:
import pandas as pd

In [171]:
df2 = pd.read_csv("df2.csv")
df2.head(2)

count_session  count_hit  channelGrouping  totals_newVisits  \
0           28.0     1816.0              2.0               0.0   
1            2.0      299.0              2.0               0.0   

   device_browser  device_operatingSystem  device_isMobile  \
0             1.0                     1.0             True   
1             1.0                     1.0             True   

   device_deviceCategory  geoNetwork_region  geoNetwork_latitude  ...  \
0                    1.0                2.0              25.4052  ...   
1                    1.0                1.0              24.4539  ...   

   latest_isTrueDirect  bounces  time_on_site  transactionRevenue  \
0                 True      0.0       77417.0        1.477195e+09   
1                 True      0.0        1576.0        0.000000e+00   

   products_array  has_converted  target_date  avg_session_time_binned  \
0           898.0            1.0   2021-01-01                        1   
1          2234.0            0.0   2021-01-01                        1   

   count_hit_binned  num_interactions_binned  
0                 3                        2  
1                 2                        1  

[2 rows x 47 columns]

In [196]:
df1[column].unique()

array(['low'], dtype=object)

In [172]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score

In [173]:
# selected_features
# sessionQualityDim
# avg_session_time_binned
# single_page_rate
# count_hit_binned
# num_interactions_binned


In [174]:
selected_features = ['sessionQualityDim', 'avg_session_time_binned', 'single_page_rate', 'count_hit_binned', 'num_interactions_binned']
X = df2[selected_features]
y = df2['has_converted']

In [175]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [176]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [177]:
# Initialize the RandomForestClassifier
RFC = RandomForestClassifier()

# Fit the model on the training set
RFC.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = RFC.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Get feature importances
feature_importances = RFC.feature_importances_
print("Feature Importances:")
for feature, importance in zip(selected_features, feature_importances):
    print(f"{feature}: {importance}")


Accuracy: 0.8589626933575978
Feature Importances:
sessionQualityDim: 0.38217643871748175
avg_session_time_binned: 0.031010722490313197
single_page_rate: 0.42088070739191535
count_hit_binned: 0.049491622401802715
num_interactions_binned: 0.11644050899848707


In [178]:
# Calculate precision, recall, and F1-score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# Feature importances
feature_importances = {
    'sessionQualityDim': 0.19338234524186065,
    'avg_session_time': 0.21958626982968277,
    'single_page_rate': 0.1566488109381351,
    'count_hit': 0.19458874134598625,
    'num_interactions': 0.23579383264433512
}

Precision: 0.8137624861265261
Recall: 0.9560568522623549
F1 Score: 0.8791893998441154


In [179]:
# Initialize the RandomForestClassifier
RFC = RandomForestClassifier()

# Fit the model on the training set
RFC.fit(X_train, y_train)

# Make predictions on the test set
y_pred = RFC.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Get feature importances
feature_importances = RFC.feature_importances_

Accuracy: 0.8592426681598656


In [180]:
# Sort feature importances in descending order
sorted_indices = feature_importances.argsort()[::-1]
sorted_feature_importances = feature_importances[sorted_indices]
sorted_features = X.columns[sorted_indices]

In [181]:
# Select top N features
top_n = 5
selected_features = sorted_features[:top_n]
print("Selected Features:", selected_features)

Selected Features: Index(['single_page_rate', 'sessionQualityDim', 'num_interactions_binned',
       'count_hit_binned', 'avg_session_time_binned'],
      dtype='object')


In [182]:
# Alternatively, you can specify a threshold for feature importance and select features above that threshold
threshold = 0.1
selected_features_above_threshold = sorted_features[sorted_feature_importances > threshold]
print("Selected Features above threshold:", selected_features_above_threshold)

Selected Features above threshold: Index(['single_page_rate', 'sessionQualityDim', 'num_interactions_binned'], dtype='object')


In [184]:
# Remove less important features
# For example, let's remove features with importance below a certain threshold (e.g., 0.05)
threshold = 0.05
selected_features = sorted_features[sorted_feature_importances >= threshold]
print("Selected Features after removing less important features:", selected_features)

Selected Features after removing less important features: Index(['single_page_rate', 'sessionQualityDim', 'num_interactions_binned',
       'count_hit_binned'],
      dtype='object')


In [185]:
import pickle
with open('random_forest_model.pkl', 'wb') as model_file:
    pickle.dump(RFC, model_file)

In [189]:
# Importing the required library
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the RandomForestClassifier
random_forest_classifier = RandomForestClassifier()

# Train the classifier
random_forest_classifier.fit(X_train, y_train)

# Predict probabilities
predictions = random_forest_classifier.predict(X_test)
predicted_probabilities = random_forest_classifier.predict_proba(X_test)


In [191]:
predicted_probabilities

array([[0.02      , 0.98      ],
       [0.43880931, 0.56119069],
       [0.16314335, 0.83685665],
       ...,
       [1.        , 0.        ],
       [0.16839406, 0.83160594],
       [1.        , 0.        ]])

Another model build-Its my own knowldege

In [186]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Initialize models
models = {
    "RandomForest": RandomForestClassifier(),
    "GradientBoosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVC": SVC(),
    "KNeighbors": KNeighborsClassifier()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy:", accuracy)


RandomForest Accuracy: 0.8593826555609995
GradientBoosting Accuracy: 0.8129068383845454


c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost Accuracy: 0.7952684258416742
SVC Accuracy: 0.769510744033037
KNeighbors Accuracy: 0.8434240918317352


KNeighborsclassifiers model-2

In [2]:
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score

In [10]:
# Initialize the KNeighborsClassifier
KNN = KNeighborsClassifier()

# Fit the model on the training set
KNN.fit(X_train, y_train)

# Make predictions on the test set
y_pred = KNN.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9686174724342663


In [12]:
import pickle
# Save the trained model to a file
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(KNN, file)

GradientBoosting Accuracy model-3

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
# Initialize the GradientBoostingClassifier
GB = GradientBoostingClassifier()

# Fit the model on the training set
GB.fit(X_train, y_train)

# Make predictions on the test set
y_pred_GB = GB.predict(X_test)

# Evaluate the model
accuracy_GB = accuracy_score(y_test, y_pred_GB)
print("GradientBoosting Accuracy:", accuracy_GB)

GradientBoosting Accuracy: 0.8454905286966355


In [15]:
# Save the trained model to a file
with open('gradient_boosting_model.pkl', 'wb') as file:
    pickle.dump(GB, file)

AdaBoost Accuracy model-4

In [16]:
from sklearn.ensemble import AdaBoostClassifier

# Initialize the AdaBoostClassifier
AdaBoost = AdaBoostClassifier()

# Fit the model on the training set
AdaBoost.fit(X_train, y_train)

# Make predictions on the test set
y_pred_AdaBoost = AdaBoost.predict(X_test)

# Evaluate the model
accuracy_AdaBoost = accuracy_score(y_test, y_pred_AdaBoost)
print("AdaBoost Accuracy:", accuracy_AdaBoost)

c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost Accuracy: 0.7965083404014702


In [17]:
# Save the trained model to a file
with open('adaboost_model.pkl', 'wb') as file:
    pickle.dump(AdaBoost, file)

SVC Accuracy model-5

In [18]:
from sklearn.svm import SVC

# Initialize the SVC
SVC_model = SVC()

# Fit the model on the training set
SVC_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_SVC = SVC_model.predict(X_test)

# Evaluate the model
accuracy_SVC = accuracy_score(y_test, y_pred_SVC)
print("SVC Accuracy:", accuracy_SVC)

SVC Accuracy: 0.7225049476957874


In [19]:
# Save the trained model to a file
with open('svc_model.pkl', 'wb') as file:
    pickle.dump(SVC_model, file)

Get results

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [22]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the classifiers
classifiers = {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier()
}

# Train and evaluate each model
results = {}
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    results[name] = {'Accuracy': accuracy, 'Precision': precision, 'Recall': recall, 'F1 Score': f1}

# Print the results
for name, metrics in results.items():
    print(f"Model: {name}")
    for metric, value in metrics.items():
        print(f"{metric}: {value}")
    print()


c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Model: Random Forest
Accuracy: 0.993214588634436
Precision: 0.9954871250331829
Recall: 0.9918011108172441
F1 Score: 0.9936406995230525

Model: Logistic Regression
Accuracy: 0.754594288945434
Precision: 0.7313348416289592
Recall: 0.8549325575244644
F1 Score: 0.7883184977441775

Model: Support Vector Machine
Accuracy: 0.7225049476957874
Precision: 0.7336160370084811
Recall: 0.7549590055540862
F1 Score: 0.7441345151199166

Model: K-Nearest Neighbors
Accuracy: 0.9686174724342663
Precision: 0.9670603674540682
Recall: 0.9744776514149696
F1 Score: 0.9707548412593862

Model: Decision Tree
Accuracy: 0.989821882951654
Precision: 0.9913884472708002
Recall: 0.9895530282993917
F1 Score: 0.9904698874917274



Gridsearchcv

In [29]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for each model
param_grid = {
    "RandomForest": {
        "n_estimators": [50, 100, 150],
        "max_depth": [None, 10, 20]
    },
    "GradientBoosting": {
        "n_estimators": [50, 100, 150],
        "learning_rate": [0.01, 0.1, 1.0]
    },
    "AdaBoost": {
        "n_estimators": [50, 100, 150],
        "learning_rate": [0.01, 0.1, 1.0]
    },
    "SVC": {
        "C": [0.1, 1, 10],
        "kernel": ["linear", "rbf"]
    },
    "KNeighbors": {
        "n_neighbors": [3, 5, 7],
        "weights": ["uniform", "distance"]
    }
}

In [30]:
# Initialize models
models = {
    "RandomForest": RandomForestClassifier(),
    "GradientBoosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVC": SVC(),
    "KNeighbors": KNeighborsClassifier()
}

Hyperparameter tuning

In [31]:
from sklearn.model_selection import GridSearchCV
import joblib

# Initialize GridSearchCV for each model
best_models = {}
for name, model in models.items():
    grid_search = GridSearchCV(model, param_grid[name], cv=5, scoring='accuracy')
    grid_search.fit(X_train, y_train)
    best_models[name] = grid_search.best_estimator_

# Save the best models using joblib
for name, model in best_models.items():
    joblib.dump(model, f"{name}_best_model.pkl")

# Now you can load the best models whenever needed
loaded_models = {}
for name in best_models:
    loaded_models[name] = joblib.load(f"{name}_best_model.pkl")


c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Tprab\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is 

st page creation

Prediction Page

In [ ]:
import streamlit as st
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [192]:
def predict(model, features):
    # Create a DataFrame from the selected features
    df = pd.DataFrame(features, columns=['sessionQualityDim', 'avg_session_time_binned', 'single_page_rate', 'count_hit_binned', 'num_interactions_binned'])

    # Predict with the model
    prediction = model.predict(df)
    prediction_proba = model.predict_proba(df)[:, 1]  # Probability of positive class
    return prediction, prediction_proba


def load_model(filename):
    with open(filename, 'rb') as file:
        model = pickle.load(file)
    return model

model = load_model('random_forest_model.pkl')

def page4():
    st.title("Prediction")

    # Selectbox options for each feature
    num_interactions_options = [1, 2, 3]
    avg_session_time_options = [1, 2, 3]
    sessionQualityDim_options = [1,2,3,4,5,6,7,9,8]  # Replace with actual values
    count_hit_options = [1, 2, 3]
    single_page_rate_options = [1,2,3,4,5,6,7,9,8]  # Replace with actual values

    selected_num_interactions = st.selectbox('SELECT NUM INTERACTIONS', options=num_interactions_options)
    selected_avg_session_time = st.selectbox('SELECT AVG SESSION TIME', options=avg_session_time_options)
    selected_sessionQualityDim = st.selectbox('SELECT QUALITY DIM', options=sessionQualityDim_options)
    selected_count_hit = st.selectbox('SELECT COUNT HIT', options=count_hit_options)
    selected_single_page_rate = st.selectbox('SELECT SINGLE PAGE RATE', options=single_page_rate_options)

    # Button to trigger prediction
    if st.button('Predict'):
        # Get predictions and prediction probabilities
        features = np.array([[selected_num_interactions, selected_avg_session_time, 
                              selected_sessionQualityDim, selected_count_hit, 
                              selected_single_page_rate]])

        # Ensure correct feature names and order
        feature_names = ['num_interactions', 'avg_session_time', 'sessionQualityDim', 'count_hit', 'single_page_rate']
        features_df = pd.DataFrame(features, columns=feature_names)

        # Predict
        prediction, prediction_proba = predict(model, features_df)
        
        # Display predictions
        st.write('Prediction:', "Convert" if prediction == 1 else "Not Convert")
        st.write('Prediction Probability:', prediction_proba)